apiVersion: v1
kind: Service
metadata:
  name: vsftpd
  namespace: ftp
  annotations:
    metallb.io/loadBalancerIPs: "192.168.3.42"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: vsftpd
  ports:
    - name: ftp-ctrl
      port: 21
      targetPort: 21
      protocol: TCP
    - name: pasv-30000
      port: 30000
      targetPort: 30000
      protocol: TCP
    - name: pasv-30001
      port: 30001
      targetPort: 30001
      protocol: TCP
    - name: pasv-30002
      port: 30002
      targetPort: 30002
      protocol: TCP
    - name: pasv-30003
      port: 30003
      targetPort: 30003
      protocol: TCP
    - name: pasv-30004
      port: 30004
      targetPort: 30004
      protocol: TCP
    - name: pasv-30005
      port: 30005
      targetPort: 30005
      protocol: TCP
    - name: pasv-30006
      port: 30006
      targetPort: 30006
      protocol: TCP
    - name: pasv-30007
      port: 30007
      targetPort: 30007
      protocol: TCP
    - name: pasv-30008
      port: 30008
      targetPort: 30008
      protocol: TCP
    - name: pasv-30009
      port: 30009
      targetPort: 30009
      protocol: TCP
    - name: pasv-30010
      port: 30010
      targetPort: 30010
      protocol: TCP
    - name: pasv-30011
      port: 30011
      targetPort: 30011
      protocol: TCP
    - name: pasv-30012
      port: 30012
      targetPort: 30012
      protocol: TCP
    - name: pasv-30013
      port: 30013
      targetPort: 30013
      protocol: TCP
    - name: pasv-30014
      port: 30014
      targetPort: 30014
      protocol: TCP
    - name: pasv-30015
      port: 30015
      targetPort: 30015
      protocol: TCP
    - name: pasv-30016
      port: 30016
      targetPort: 30016
      protocol: TCP
    - name: pasv-30017
      port: 30017
      targetPort: 30017
      protocol: TCP
    - name: pasv-30018
      port: 30018
      targetPort: 30018
      protocol: TCP
    - name: pasv-30019
      port: 30019
      targetPort: 30019
      protocol: TCP
    - name: pasv-30020
      port: 30020
      targetPort: 30020
      protocol: TCP
    - name: pasv-30021
      port: 30021
      targetPort: 30021
      protocol: TCP
    - name: pasv-30022
      port: 30022
      targetPort: 30022
      protocol: TCP
    - name: pasv-30023
      port: 30023
      targetPort: 30023
      protocol: TCP
    - name: pasv-30024
      port: 30024
      targetPort: 30024
      protocol: TCP
    - name: pasv-30025
      port: 30025
      targetPort: 30025
      protocol: TCP
    - name: pasv-30026
      port: 30026
      targetPort: 30026
      protocol: TCP
    - name: pasv-30027
      port: 30027
      targetPort: 30027
      protocol: TCP
    - name: pasv-30028
      port: 30028
      targetPort: 30028
      protocol: TCP
    - name: pasv-30029
      port: 30029
      targetPort: 30029
      protocol: TCP
    - name: pasv-30030
      port: 30030
      targetPort: 30030
      protocol: TCP
    - name: pasv-30031
      port: 30031
      targetPort: 30031
      protocol: TCP
    - name: pasv-30032
      port: 30032
      targetPort: 30032
      protocol: TCP
    - name: pasv-30033
      port: 30033
      targetPort: 30033
      protocol: TCP
    - name: pasv-30034
      port: 30034
      targetPort: 30034
      protocol: TCP
    - name: pasv-30035
      port: 30035
      targetPort: 30035
      protocol: TCP
    - name: pasv-30036
      port: 30036
      targetPort: 30036
      protocol: TCP
    - name: pasv-30037
      port: 30037
      targetPort: 30037
      protocol: TCP
    - name: pasv-30038
      port: 30038
      targetPort: 30038
      protocol: TCP
    - name: pasv-30039
      port: 30039
      targetPort: 30039
      protocol: TCP
    - name: pasv-30040
      port: 30040
      targetPort: 30040
      protocol: TCP
    - name: pasv-30041
      port: 30041
      targetPort: 30041
      protocol: TCP
    - name: pasv-30042
      port: 30042
      targetPort: 30042
      protocol: TCP
    - name: pasv-30043
      port: 30043
      targetPort: 30043
      protocol: TCP
    - name: pasv-30044
      port: 30044
      targetPort: 30044
      protocol: TCP
    - name: pasv-30045
      port: 30045
      targetPort: 30045
      protocol: TCP
    - name: pasv-30046
      port: 30046
      targetPort: 30046
      protocol: TCP
    - name: pasv-30047
      port: 30047
      targetPort: 30047
      protocol: TCP
    - name: pasv-30048
      port: 30048
      targetPort: 30048
      protocol: TCP
    - name: pasv-30049
      port: 30049
      targetPort: 30049
      protocol: TCP
    - name: pasv-30050
      port: 30050
      targetPort: 30050
      protocol: TCP
    - name: pasv-30051
      port: 30051
      targetPort: 30051
      protocol: TCP
    - name: pasv-30052
      port: 30052
      targetPort: 30052
      protocol: TCP
    - name: pasv-30053
      port: 30053
      targetPort: 30053
      protocol: TCP
    - name: pasv-30054
      port: 30054
      targetPort: 30054
      protocol: TCP
    - name: pasv-30055
      port: 30055
      targetPort: 30055
      protocol: TCP
    - name: pasv-30056
      port: 30056
      targetPort: 30056
      protocol: TCP
    - name: pasv-30057
      port: 30057
      targetPort: 30057
      protocol: TCP
    - name: pasv-30058
      port: 30058
      targetPort: 30058
      protocol: TCP
    - name: pasv-30059
      port: 30059
      targetPort: 30059
      protocol: TCP
    - name: pasv-30060
      port: 30060
      targetPort: 30060
      protocol: TCP
    - name: pasv-30061
      port: 30061
      targetPort: 30061
      protocol: TCP
    - name: pasv-30062
      port: 30062
      targetPort: 30062
      protocol: TCP
    - name: pasv-30063
      port: 30063
      targetPort: 30063
      protocol: TCP
    - name: pasv-30064
      port: 30064
      targetPort: 30064
      protocol: TCP
    - name: pasv-30065
      port: 30065
      targetPort: 30065
      protocol: TCP
    - name: pasv-30066
      port: 30066
      targetPort: 30066
      protocol: TCP
    - name: pasv-30067
      port: 30067
      targetPort: 30067
      protocol: TCP
    - name: pasv-30068
      port: 30068
      targetPort: 30068
      protocol: TCP
    - name: pasv-30069
      port: 30069
      targetPort: 30069
      protocol: TCP
    - name: pasv-30070
      port: 30070
      targetPort: 30070
      protocol: TCP
    - name: pasv-30071
      port: 30071
      targetPort: 30071
      protocol: TCP
    - name: pasv-30072
      port: 30072
      targetPort: 30072
      protocol: TCP
    - name: pasv-30073
      port: 30073
      targetPort: 30073
      protocol: TCP
    - name: pasv-30074
      port: 30074
      targetPort: 30074
      protocol: TCP
    - name: pasv-30075
      port: 30075
      targetPort: 30075
      protocol: TCP
    - name: pasv-30076
      port: 30076
      targetPort: 30076
      protocol: TCP
    - name: pasv-30077
      port: 30077
      targetPort: 30077
      protocol: TCP
    - name: pasv-30078
      port: 30078
      targetPort: 30078
      protocol: TCP
    - name: pasv-30079
      port: 30079
      targetPort: 30079
      protocol: TCP
    - name: pasv-30080
      port: 30080
      targetPort: 30080
      protocol: TCP
    - name: pasv-30081
      port: 30081
      targetPort: 30081
      protocol: TCP
    - name: pasv-30082
      port: 30082
      targetPort: 30082
      protocol: TCP
    - name: pasv-30083
      port: 30083
      targetPort: 30083
      protocol: TCP
    - name: pasv-30084
      port: 30084
      targetPort: 30084
      protocol: TCP
    - name: pasv-30085
      port: 30085
      targetPort: 30085
      protocol: TCP
    - name: pasv-30086
      port: 30086
      targetPort: 30086
      protocol: TCP
    - name: pasv-30087
      port: 30087
      targetPort: 30087
      protocol: TCP
    - name: pasv-30088
      port: 30088
      targetPort: 30088
      protocol: TCP
    - name: pasv-30089
      port: 30089
      targetPort: 30089
      protocol: TCP
    - name: pasv-30090
      port: 30090
      targetPort: 30090
      protocol: TCP
    - name: pasv-30091
      port: 30091
      targetPort: 30091
      protocol: TCP
    - name: pasv-30092
      port: 30092
      targetPort: 30092
      protocol: TCP
    - name: pasv-30093
      port: 30093
      targetPort: 30093
      protocol: TCP
    - name: pasv-30094
      port: 30094
      targetPort: 30094
      protocol: TCP
    - name: pasv-30095
      port: 30095
      targetPort: 30095
      protocol: TCP
    - name: pasv-30096
      port: 30096
      targetPort: 30096
      protocol: TCP
    - name: pasv-30097
      port: 30097
      targetPort: 30097
      protocol: TCP
    - name: pasv-30098
      port: 30098
      targetPort: 30098
      protocol: TCP
    - name: pasv-30099
      port: 30099
      targetPort: 30099
      protocol: TCP
